development:
  sessions:
    default:
      database: ojstats
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: ojstats_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: ojstats
      hosts:
        - localhost:27017
