development:
  host: localhost
  database: ojstats_development

test:
  host: localhost
  database: ojstats_test

# set these environment variables on your prod server
production:
  host: localhost
  database: ojstats
